# Generated by Django 3.2 on 2022-02-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='carpeta_pare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arxius.carpeta'),
        ),
    ]
