# Generated by Django 3.2 on 2022-02-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arxius', '0003_auto_20220210_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpeta',
            options={'verbose_name_plural': 'carpetes'},
        ),
    ]
